[tool.black]
line-length = 88
required-version = "22.1.0"
target_version = ['py36', 'py37', 'py38', 'py39', 'py310']

[tool.isort]
profile = 'black'  # sets line-length to 88
case_sensitive = true
skip = "__init__.py"
skip_gitignore = true
