jobs:
  - job: 'dagster'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
    #     Python27:
    #       python.version: '2.7'
    #     Python35:
    #       python.version: '3.5'
        Python36:
          python.version: '3.6'
          TOXENV: 'py36'
    #     Python37:
    #       python.version: '3.7'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - script: pip install tox
      displayName: 'Install tox'
    - script:
      - cd python_modules\dagster && tox -e %TOXENV% && cd ..\.. 
    # - task: PublishTestResults@2
    #   inputs:
    #     testResultsFiles: '**/test-results.xml'
    #     testRunTitle: 'Python $(python.version)'
    #   condition: succeededOrFailed()
