jobs:
  - job: 'dagster'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python27:
          TOXENV: 'py27'
        Python35:
          TOXENV: 'py35'
        Python36:
          TOXENV: 'py36'
        Python37:
          TOXENV: 'py37'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
    - script: pip install tox
      displayName: 'Install tox'
    - script: cd python_modules\dagster && tox -e %TOXENV% && cd ..\.. 
      displayName: 'Run tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/test-results.xml'
        testRunTitle: 'Python $(python.version)'
      condition: succeededOrFailed()
