[tool.black]
line-length = 100
exclude = '''
/(
    build/
  | buck-out/
  | dist/
  | _build/
  | \.eggs/
  | \.git/
  | \.hg/
  | \.mypy_cache/
  | \.nox/
  | \.tox/
  | \.venv/
  | python_modules/dagster/dagster/tutorials/
  | snapshots/
  | __scaffold\.py
/)
'''
