context:
  default:
    config:
      log_level: DEBUG
expectations:
  evaluate: false
solids:
  event_ingest:
    inputs:
      spark_inputs: ["foo"]
    config:
      spark_outputs: ["bar"]
      application_arguments: "--local-path /data/ --date 2019-01-01"
      application_jar: "./events-assembly-0.1.0-SNAPSHOT.jar"
      main_class: "io.dagster.events.EventPipeline"
      master_url: "local[4]"


# TODO: set up tests on remote cluster
#   application_jar: "events-assembly-0.1.0-SNAPSHOT.jar"
#   deploy_mode: "client"
#   main_class: "io.dagster.events.EventPipeline"
#   application_arguments: "--s3-bucket elementl-data --s3-prefix events --date 2019-01-01"            
#   master_url: "spark://127.0.0.1:7077"
#   spark_conf:
#     spark:
#       app:
#         name: "test_app"
#       executor:
#         cores: 1
