[project]
name = "with_pyspark"
version = "0.1.0"
description = "Example Dagster project demonstrating PySpark."
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [
    "dagster",
    "dagster-spark",
    "dagster-pyspark",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "with_pyspark"

[tool.setuptools.packages.find]
exclude = ["with_pyspark_tests"]
