version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
      - image: circleci/buildpack-deps:18.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox

      - run:
          name: Run Dagster Tests
          command: |
            . venv/bin/activate
            cd python_modules/dagster
            tox

      - run:
          name: Run Dagit Tests
          command: |
            . venv/bin/activate
            cd python_modules/dagit
            tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
