[project]
name = "project_ask_ai_dagster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "langchain",
    "gql",
    "python-dotenv",
    "langchain-community",
    "langchain-openai",
    "dagster",
    "chromadb",
    "tenacity",
    "tqdm"
    "bs4",
    "lxml",
    "openai"
    ]

[project.optional-dependencies]
dev = [
    "dagster-webserver",
    "pytest",
    "ruff",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "project_ask_ai_dagster.definitions"
project_name = "project_ask_ai_dagster"

[tool.setuptools.packages.find]
exclude=["project_ask_ai_dagster"]
