version: "3.7"

services:
  test-mysql-db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: test-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_DATABASE: "test"
    networks:
      - mysql

  test-mysql-db-backcompat:
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: test-mysql-db-backcompat
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_DATABASE: "test"
      MYSQL_TCP_PORT: 3307
    expose:
      - 3307
    networks:
      - mysqlbackcompat

networks:
  mysql:
    driver: bridge
    name: mysql
  mysqlbackcompat:
    driver: bridge
    name: mysqlbackcompat
