[project]
name = "simple-migration"
readme = "README.md"
dependencies = [ "dagster", "dagster-airlift[core,in-airflow]", "dagster-webserver",]
requires-python = ">=3.11"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.optional-dependencies]
test = [ "pytest",]
