[project]
name = "dagster-azure"
version = "1!0+dev"
description = "Package for Azure-specific Dagster framework op and resource components."
readme = "README.md"
classifiers = [ "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9",]
requires-python = ">=3.8,<3.13"
dependencies = [ "azure-core<2.0.0,>=1.7.0", "azure-identity<2.0.0,>=1.7.0", "azure-storage-blob<13.0.0,>=12.5.0", "azure-storage-file-datalake<13.0.0,>=12.5", "dagster",]
[[project.authors]]
name = "Dagster Labs"
email = "hello@dagsterlabs.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.license]
text = "Apache-2.0"

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-azure"

[project.scripts]
dagster-azure = "dagster_azure.cli.cli:main"
