[project]
name = "quickstart_gcp"
version = "0.1.0"
description = "Dagster project for GCP quickstart."
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [
    "boto3",  # used by Dagster Cloud Serverless
    "dagster",
    "dagster-cloud",
    "dagster-gcp",
    "dagster-gcp-pandas",
    "google-auth",
    "matplotlib",
    "pandas",
    "pandas_gbq",
    "textblob",
    "tweepy",
    "wordcloud",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "quickstart_gcp.definitions"
code_location_name = "quickstart_gcp"

[tool.setuptools.packages.find]
exclude = ["quickstart_gcp_tests"]
