nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: '*'
  babel-plugin-graphql-tag@*:
    dependencies:
      graphql: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: '*'
  graphql.macro@*:
    dependencies:
      '@babel/core': '*'
      '@babel/runtime': '*'
      graphql: '*'
  styled-components@*:
    dependencies:
      babel-plugin-macros: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
