nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  '@blueprintjs/popover2@*':
    peerDependencies:
      react-dom: '*'
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    dependencies:
      typescript: '*'
  '@mdx-js/loader@*':
    peerDependencies:
      react: '*'
  apollo-link-context@*:
    peerDependencies:
      graphql: '*'
  apollo-link-error@*:
    peerDependencies:
      graphql: '*'
  babel-plugin-graphql-tag@*:
    dependencies:
      graphql: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: '*'
  graphql.macro@*:
    dependencies:
      '@babel/core': '*'
      '@babel/runtime': '*'
      graphql: '*'
  react-dev-utils@*:
    peerDependencies:
      typescript: '*'
      webpack: '*'
  styled-components@*:
    dependencies:
      babel-plugin-macros: '*'
  '@storybook/core-common@*':
    dependencies:
      '@storybook/react-webpack5': '7.0.8'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
