[project]
name = "external_assets"
version = "0.1.0"
license = "Apache-2.0"
description = "Dagster example of yaml dsl for building external_assets"
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [
    "dagster>=1.5.1", 
    "dagster-k8s>=0.21.1",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
