[project]
name = "assets_yaml_dsl"
version = "0.1.0"
license = "Apache-2.0"
description = "Dagster example of yaml dsl for building asset graphs"
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [
    "dagster",
    "dagster-pipes",
    "pandas",
]

[project.urls]
url = "https://github.com/dagster-io/dagster/tree/master/examples/assets_yaml_dsl"

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "assets_yaml_dsl.definitions"
code_location_name = "assets_yaml_dsl"

[tool.setuptools.packages.find]
exclude = ["assets_yaml_dsl_tests"]
