compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "@blueprintjs/popover2@*":
    peerDependencies:
      react-dom: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  apollo-link-context@*:
    peerDependencies:
      graphql: "*"
  apollo-link-error@*:
    peerDependencies:
      graphql: "*"
  babel-plugin-graphql-tag@*:
    dependencies:
      graphql: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  eslint-plugin-prettier@*:
    dependencies:
      eslint-config-prettier: "*"
  graphql.macro@*:
    dependencies:
      "@babel/core": "*"
      "@babel/runtime": "*"
      graphql: "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  styled-components@*:
    dependencies:
      babel-plugin-macros: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
