[project]
name = "dagster-webserver"
description = "Web UI for dagster."
readme = "README.rst"
classifiers = [ "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9",]
requires-python = ">=3.8,<3.13"
dependencies = [ "click>=7.0,<9.0", "dagster", "dagster-graphql", "starlette!=0.36.0", "uvicorn[standard]",]
version = "1!0+dev"
[[project.authors]]
name = "Dagster Labs"
email = "hello@dagsterlabs.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.license]
text = "Apache-2.0"

[project.urls]
Homepage = "https://github.com/dagster-io/dagster"

[project.optional-dependencies]
notebook = [ "nbconvert",]
test = [ "starlette[full]",]

[project.scripts]
dagster-webserver = "dagster_webserver.cli:main"
dagster-webserver-debug = "dagster_webserver.debug:main"
