[project]
name = "dagster-deltalake"
version = "1!0+dev"
description = "Package for Deltalake-specific Dagster framework op and resource components."
readme = "README.md"
classifiers = [ "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9",]
requires-python = ">=3.8,<3.13"
dependencies = [ "dagster", "deltalake>=0.15,<0.18",]
[[project.authors]]
name = "Elementl"
email = "hello@elementl.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.license]
text = "Apache-2.0"

[project.urls]
Homepage = "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-deltalake"

[project.optional-dependencies]
pandas = [ "pandas",]
