[project]
name = "dagster_university"
version = "0.1.0"
description = "Dagster project for AWS quickstart."
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [
    "dagster==1.7.*",
    "dagster-cloud",
    "dagster-duckdb",
    "geopandas",
    "kaleido",
    "pandas",
    "plotly",
    "shapely",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "dagster_university"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint]
extend-ignore = [

  # (Unused import): We stub some files with just imports to help people get started
  "F401",    
  # (Import block is un-sorted or un-formatted): It's more important that we introduce the imports in the order they're used rather than alphabetically.
  "I001",

  # (relative imports): relative imports are acceptable in examples & docs
  "TID252"

]

[tool.setuptools.packages.find]
exclude = ["dagster_university_tests"]
