[project]
name = "quickstart_aws"
version = "0.1.0"
description = "Dagster project for AWS quickstart."
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = [
    "dagster",
    "dagster-aws",
    "dagster-cloud",
    "matplotlib",
    "pandas",
    "wordcloud",
]

[project.optional-dependencies]
dev = ["dagster-webserver", "pytest"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "quickstart_aws.definitions"
code_location_name = "quickstart_aws"

[tool.setuptools.packages.find]
exclude = ["quickstart_aws_tests"]
